In [1]:
import pandas as pd

In [32]:
df = pd.read_csv('student.csv')
print(df)

     StudentID         Name  Age Gender        Department  Math  Physics  \
0         1001     Student1   24    NaN               NaN   NaN      NaN
1         1002     Student2   21      F           Biology  52.0     43.0
2         1003     Student3   22      M  Computer Science  60.0     76.0
3         1004     Student4   24      M  Computer Science  47.0     95.0
4         1005     Student5   20      M  Computer Science  85.0     40.0
..         ...          ...  ...    ...               ...   ...      ...
995       1996   Student996   23      F       Mathematics  78.0     75.0
996       1997   Student997   18      F  Computer Science  73.0     86.0
997       1998   Student998   24      M         Chemistry  95.0     80.0
998       1999   Student999   21      M  Computer Science  67.0     44.0
999       2000  Student1000   23      F       Mathematics  76.0     52.0

     Chemistry  Attendance       City
0          NaN         NaN        NaN
1         97.0        69.0        NaN
2         89.0        81.0      Delhi
3         69.0        78.0      Delhi
4         76.0        60.0     Mumbai
..         ...         ...        ...
995       83.0        97.0     Mumbai
996       44.0        82.0    Kolkata
997       62.0        84.0  Bangalore
998       80.0        66.0     Mumbai
999       98.0        81.0    Kolkata

[1000 rows x 10 columns]

In [6]:
df.head(5)
df.tail(5)
df.describe()

,StudentID,Age,Math,Physics,Chemistry,Attendance
count,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000
mean,1500.500000,20.9600,69.979000,70.025000,69.927000,79.779000
std,288.819436,2.0036,17.172112,17.238084,17.730991,11.319553
min,1001.000000,18.0000,40.000000,40.000000,40.000000,60.000000
25%,1250.750000,19.0000,56.000000,56.000000,55.000000,71.000000
50%,1500.500000,21.0000,69.000000,70.000000,69.000000,79.000000
75%,1750.250000,23.0000,85.000000,85.000000,86.000000,89.250000
max,2000.000000,24.0000,99.000000,99.000000,99.000000,99.000000

In [7]:
df.dtypes

StudentID      int64
Name          object
Age            int64
Gender        object
Department    object
Math           int64
Physics        int64
Chemistry      int64
Attendance     int64
City          object
dtype: object

In [25]:
## handling missing values
df.isnull()

,StudentID,Name,Age,Gender,Department,Math,Physics,Chemistry,Attendance,City
0,False,False,False,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False
996,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False
998,False,False,False,False,False,False,False,False,False,False
999,False,False,False,False,False,False,False,False,False,False

In [33]:
df.isnull().any(
    axis=0
)
df.isnull().sum()

StudentID     0
Name          0
Age           0
Gender        1
Department    1
Math          1
Physics       1
Chemistry     1
Attendance    1
City          2
dtype: int64

In [34]:
df.fillna(0)

,StudentID,Name,Age,Gender,Department,Math,Physics,Chemistry,Attendance,City
0,1001,Student1,24,0,0,0.0,0.0,0.0,0.0,0
1,1002,Student2,21,F,Biology,52.0,43.0,97.0,69.0,0
2,1003,Student3,22,M,Computer Science,60.0,76.0,89.0,81.0,Delhi
3,1004,Student4,24,M,Computer Science,47.0,95.0,69.0,78.0,Delhi
4,1005,Student5,20,M,Computer Science,85.0,40.0,76.0,60.0,Mumbai
...,...,...,...,...,...,...,...,...,...,...
995,1996,Student996,23,F,Mathematics,78.0,75.0,83.0,97.0,Mumbai
996,1997,Student997,18,F,Computer Science,73.0,86.0,44.0,82.0,Kolkata
997,1998,Student998,24,M,Chemistry,95.0,80.0,62.0,84.0,Bangalore
998,1999,Student999,21,M,Computer Science,67.0,44.0,80.0,66.0,Mumbai
999,2000,Student1000,23,F,Mathematics,76.0,52.0,98.0,81.0,Kolkata

In [36]:
## filling missing values with the mean of the column

df['Math'] = df['Math'].fillna(df['Math'].mean())

df

,StudentID,Name,Age,Gender,Department,Math,Physics,Chemistry,Attendance,City
0,1001,Student1,24,NaN,NaN,69.988989,NaN,NaN,NaN,NaN
1,1002,Student2,21,F,Biology,52.000000,43.0,97.0,69.0,NaN
2,1003,Student3,22,M,Computer Science,60.000000,76.0,89.0,81.0,Delhi
3,1004,Student4,24,M,Computer Science,47.000000,95.0,69.0,78.0,Delhi
4,1005,Student5,20,M,Computer Science,85.000000,40.0,76.0,60.0,Mumbai
...,...,...,...,...,...,...,...,...,...,...
995,1996,Student996,23,F,Mathematics,78.000000,75.0,83.0,97.0,Mumbai
996,1997,Student997,18,F,Computer Science,73.000000,86.0,44.0,82.0,Kolkata
997,1998,Student998,24,M,Chemistry,95.000000,80.0,62.0,84.0,Bangalore
998,1999,Student999,21,M,Computer Science,67.000000,44.0,80.0,66.0,Mumbai
999,2000,Student1000,23,F,Mathematics,76.000000,52.0,98.0,81.0,Kolkata

In [37]:
df.dtypes

StudentID       int64
Name           object
Age             int64
Gender         object
Department     object
Math          float64
Physics       float64
Chemistry     float64
Attendance    float64
City           object
dtype: object

In [45]:
## Renaming Colums

df.rename(columns={'Math': 'Mathematics'})

,StudentID,Name,Age,Gender,Department,Mathematics,Physics,Chemistry,Attendance,City
0,1001,Student1,24,NaN,NaN,69.988989,NaN,NaN,NaN,NaN
1,1002,Student2,21,F,Biology,52.000000,43.0,97.0,69.0,NaN
2,1003,Student3,22,M,Computer Science,60.000000,76.0,89.0,81.0,Delhi
3,1004,Student4,24,M,Computer Science,47.000000,95.0,69.0,78.0,Delhi
4,1005,Student5,20,M,Computer Science,85.000000,40.0,76.0,60.0,Mumbai
...,...,...,...,...,...,...,...,...,...,...
995,1996,Student996,23,F,Mathematics,78.000000,75.0,83.0,97.0,Mumbai
996,1997,Student997,18,F,Computer Science,73.000000,86.0,44.0,82.0,Kolkata
997,1998,Student998,24,M,Chemistry,95.000000,80.0,62.0,84.0,Bangalore
998,1999,Student999,21,M,Computer Science,67.000000,44.0,80.0,66.0,Mumbai
999,2000,Student1000,23,F,Mathematics,76.000000,52.0,98.0,81.0,Kolkata

In [47]:
## change data types
df['Value_new'] = df['Math'].astype('float64')
df.head()

,StudentID,Name,Age,Gender,Department,Math,Physics,Chemistry,Attendance,City,Value_new
0,1001,Student1,24,NaN,NaN,69.988989,NaN,NaN,NaN,NaN,69.988989
1,1002,Student2,21,F,Biology,52.000000,43.0,97.0,69.0,NaN,52.000000
2,1003,Student3,22,M,Computer Science,60.000000,76.0,89.0,81.0,Delhi,60.000000
3,1004,Student4,24,M,Computer Science,47.000000,95.0,69.0,78.0,Delhi,47.000000
4,1005,Student5,20,M,Computer Science,85.000000,40.0,76.0,60.0,Mumbai,85.000000

In [49]:
df['New Value'] = df['Physics'].apply(lambda x: x*2)
df

,StudentID,Name,Age,Gender,Department,Math,Physics,Chemistry,Attendance,City,Value_new,New Value
0,1001,Student1,24,NaN,NaN,69.988989,NaN,NaN,NaN,NaN,69.988989,NaN
1,1002,Student2,21,F,Biology,52.000000,43.0,97.0,69.0,NaN,52.000000,86.0
2,1003,Student3,22,M,Computer Science,60.000000,76.0,89.0,81.0,Delhi,60.000000,152.0
3,1004,Student4,24,M,Computer Science,47.000000,95.0,69.0,78.0,Delhi,47.000000,190.0
4,1005,Student5,20,M,Computer Science,85.000000,40.0,76.0,60.0,Mumbai,85.000000,80.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,1996,Student996,23,F,Mathematics,78.000000,75.0,83.0,97.0,Mumbai,78.000000,150.0
996,1997,Student997,18,F,Computer Science,73.000000,86.0,44.0,82.0,Kolkata,73.000000,172.0
997,1998,Student998,24,M,Chemistry,95.000000,80.0,62.0,84.0,Bangalore,95.000000,160.0
998,1999,Student999,21,M,Computer Science,67.000000,44.0,80.0,66.0,Mumbai,67.000000,88.0
999,2000,Student1000,23,F,Mathematics,76.000000,52.0,98.0,81.0,Kolkata,76.000000,104.0

In [56]:
## data aggregating and grouping
df.head()

grouped_mean = df.groupby('Department')['Math'].mean()
grouped_mean

Department
Biology             70.588517
Chemistry           70.169811
Computer Science    69.948718
Mathematics         70.125000
Physics             68.937143
Name: Math, dtype: float64

In [78]:
grouped_mean = df.groupby(['Department', 'Name'])['Math'].mean().reset_index()
grouped_mean.head(10)

  Department        Name  Math
0    Biology   Student10  83.0
1    Biology  Student107  97.0
2    Biology  Student109  86.0
3    Biology   Student11  71.0
4    Biology  Student111  59.0
5    Biology  Student116  65.0
6    Biology  Student118  77.0
7    Biology   Student12  50.0
8    Biology  Student125  77.0
9    Biology  Student129  96.0

In [83]:
## aggregate multiple fun

grouped_agg = df.groupby('Name')['Physics'].aggregate(['min', 'max', 'mean','sum','count'])
grouped_agg.head(199)

              min   max  mean   sum  count
Name
Student1      NaN   NaN   NaN   0.0      0
Student10    68.0  68.0  68.0  68.0      1
Student100   81.0  81.0  81.0  81.0      1
Student1000  52.0  52.0  52.0  52.0      1
Student101   73.0  73.0  73.0  73.0      1
...           ...   ...   ...   ...    ...
Student273   44.0  44.0  44.0  44.0      1
Student274   99.0  99.0  99.0  99.0      1
Student275   48.0  48.0  48.0  48.0      1
Student276   40.0  40.0  40.0  40.0      1
Student277   75.0  75.0  75.0  75.0      1

[199 rows x 5 columns]

In [97]:
## merging and joining data frame

df1= pd.DataFrame(
    {
        'key':[1,2,3,4],
        # 'values': ['A0', 'A1', 'A2', 'A3']
        'values': [1,2,3,4]
    }
)

df2= pd.DataFrame(
    {
        'key':[1,2,3,4],
        # 'values': ['A0', 'A1', 'A2', 'A3']
        'values': [1,2,3,4]
    }
)
df1

   key  values
0    1       1
1    2       2
2    3       3
3    4       4

In [98]:
## merge data frame on the key colums
pd.merge(df1, df2, how='inner', on='key')

   key  values_x  values_y
0    1         1         1
1    2         2         2
2    3         3         3
3    4         4         4